# Generated by Django 4.0.1 on 2022-02-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H_W_Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_w_send_lesson', models.CharField(max_length=100, verbose_name='Предмет')),
                ('h_w_send_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('h_w_send_text', models.TextField(verbose_name='Текст задания')),
                ('send_pub_date', models.DateTimeField(verbose_name='Число')),
            ],
            options={
                'verbose_name': 'Отправленное Д/З',
                'verbose_name_plural': 'Отправленные Д/З',
            },
        ),
    ]
