# Generated by Django 4.0.1 on 2022-02-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_w', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h_w_send',
            name='send_pub_date',
        ),
    ]
