# Generated by Django 4.0.1 on 2022-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_w', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_W_Send_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_w_send_lesson_i', models.CharField(max_length=100, verbose_name='Предмет')),
                ('h_w_send_name_i', models.CharField(max_length=100, verbose_name='ФИО')),
                ('h_w_send_text_i', models.TextField(verbose_name='Дополнительный коментарий')),
                ('h_w_send_image', models.ImageField(upload_to='works')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
