# Generated by Django 4.0.1 on 2022-02-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_w', '0004_h_w_send_image_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_W_Image_Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_w_send_image_lesson', models.CharField(max_length=100, verbose_name='Предмет')),
                ('h_w_send_image_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('h_w_send_image_text', models.TextField(verbose_name='Текст задания')),
                ('h_w_send_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Отправленное Д/З в виде фото',
                'verbose_name_plural': 'Отправленные Д/З в виде фото',
            },
        ),
        migrations.DeleteModel(
            name='H_W_Send_Image',
        ),
    ]
