# Generated by Django 4.0.1 on 2022-02-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_w_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h_w',
            options={'verbose_name': 'Д/З', 'verbose_name_plural': 'Д/З'},
        ),
    ]
