# Generated by Django 4.0.1 on 2022-02-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_w_list', '0002_alter_h_w_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_w',
            name='pub_date',
            field=models.DateField(verbose_name='дата'),
        ),
    ]
